(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "ido-ubiquitous")

;; Misc
(depends-on "atom-one-dark-theme")
(depends-on "base16-theme")
(depends-on "smex")
(depends-on "multiple-cursors")
(depends-on "company")
(depends-on "smooth-scrolling")
(depends-on "evil")
(depends-on "evil-easymotion")

;; ace
(depends-on "avy")
(depends-on "ace-window")
(depends-on "exec-path-from-shell")

;; Clojure
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "clj-refactor")
(depends-on "paredit")
(depends-on "rainbow-delimiters")

;; Haskell
(depends-on "haskell-mode")
;(depends-on "company-ghc")
(depends-on "intero")

(depends-on "markdown-mode")

;; Elixir
(depends-on "alchemist")

;; Rust
(depends-on "rust-mode")
(depends-on "racer")
(depends-on "flycheck-rust")


;; Python
(depends-on "python-mode")
(depends-on "elpy")
(depends-on "jedi")

;; dotnet
(depends-on "csharp-mode")
(depends-on "omnisharp")

(depends-on "neotree")

;; Schemes
(depends-on "racket-mode")
(depends-on "geiser")
