(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "flx")
(depends-on "flx-ido")

(depends-on "atom-one-dark-theme")

;; Clojure
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "clj-refactor")
(depends-on "paredit")

(depends-on "base16-theme")
(depends-on "rainbow-delimiters")
(depends-on "smex")
(depends-on "multiple-cursors")
(depends-on "company")

(depends-on "ace-jump-mode")
(depends-on "ace-window")
(depends-on "exec-path-from-shell")

;; Haskell
(depends-on "haskell-mode")
;(depends-on "company-ghc")
(depends-on "intero")

(depends-on "markdown-mode")

(depends-on "alchemist") ;; Elixir

(depends-on "smooth-scrolling")
